/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangelogModal: typeof import('./src/components/ChangelogModal.vue')['default']
    DropdownMenu: typeof import('./src/components/DropdownMenu.vue')['default']
    IconAbout: typeof import('./src/components/icons/IconAbout.vue')['default']
    IconArrowDown: typeof import('./src/components/icons/IconArrowDown.vue')['default']
    IconBold: typeof import('./src/components/icons/text/IconBold.vue')['default']
    IconItalics: typeof import('./src/components/icons/text/IconItalics.vue')['default']
    IconLoad: typeof import('./src/components/icons/IconLoad.vue')['default']
    IconLyricsInput: typeof import('./src/components/icons/IconLyricsInput.vue')['default']
    IconMusic: typeof import('./src/components/icons/IconMusic.vue')['default']
    IconSave: typeof import('./src/components/icons/IconSave.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    IconStrikethrough: typeof import('./src/components/icons/text/IconStrikethrough.vue')['default']
    IconUnderline: typeof import('./src/components/icons/text/IconUnderline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarLink: typeof import('./src/components/sidebar/SidebarLink.vue')['default']
    ThemeDropdownMenu: typeof import('./src/components/ThemeDropdownMenu.vue')['default']
    ToggleSwitch: typeof import('openvue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('openvue/tooltip')['default']
  }
}
