/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconAbout: typeof import('./src/components/icons/IconAbout.vue')['default']
    IconArrowDown: typeof import('./src/components/icons/IconArrowDown.vue')['default']
    IconLoad: typeof import('./src/components/icons/IconLoad.vue')['default']
    IconLyricsInput: typeof import('./src/components/icons/IconLyricsInput.vue')['default']
    IconMusic: typeof import('./src/components/icons/IconMusic.vue')['default']
    IconSave: typeof import('./src/components/icons/IconSave.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarLink: typeof import('./src/components/sidebar/SidebarLink.vue')['default']
    ThemeDropdownMenu: typeof import('./src/components/ThemeDropdownMenu.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
